import test from "node:test";
import assert from "node:assert/strict";
import {emptyStore,newSession,isStore,countSets,workouts,nextAim,sortedHistory,sessionDate} from "../lib/workouts.ts";
test("sessions have independent sets and categories",()=>{const push=newSession("Push",{});const pull=newSession("Pull",{});push.exercises.incline[0].done=true;assert.equal(countSets(push),1);assert.equal(countSets(pull),0);assert.equal(push.exercises.incline[1].done,false);assert.equal(workouts.Push.length,4);assert.equal(workouts.Pull.length,3);assert.equal(workouts.Legs.length,3);});
test("stored progress round-trips and remembers half-kilogram loads",()=>{const s=emptyStore();s.active.Push=newSession("Push",{incline:7.5});s.active.Push.exercises.incline[0]={kg:7.5,reps:10,done:true};const restored=JSON.parse(JSON.stringify(s));assert.ok(isStore(restored));assert.equal(restored.active.Push.exercises.incline[0].kg,7.5);assert.equal(countSets(restored.active.Push),1);});
test("corrupt persisted data is rejected before rendering",()=>{for(const value of [null,{},[],{...emptyStore(),version:2},{...emptyStore(),selected:"unknown"}])assert.equal(isStore(value),false);const s=emptyStore();s.active.Legs=newSession("Legs",{});s.active.Legs.exercises.squat[0].kg=-1;assert.equal(isStore(s),false);s.active.Legs.exercises.squat[0].kg=6;s.active.Legs.exercises.squat[0].reps=2.5;assert.equal(isStore(s),false);delete s.active.Legs.exercises.rdl;assert.equal(isStore(s),false);});
test("bodyweight and finished-session history remain valid",()=>{const s=emptyStore();const session=newSession("Legs",{});assert.equal(session.exercises.lunge[0].kg,0);for(const sets of Object.values(session.exercises))for(const set of sets)set.done=true;session.finishedAt=new Date().toISOString();s.history.push(session);assert.equal(countSets(session),9);assert.ok(isStore(s));});

test("Full Body combines four free-weight exercises with independent logs",()=>{const full=newSession("Full Body",{squat:8},"2026-09-19");const legs=newSession("Legs",{});assert.equal(full.date,"2026-09-19");assert.equal(Object.keys(full.exercises).length,4);full.exercises.squat[0].done=true;assert.equal(countSets(legs),0);const store=emptyStore();store.active["Full Body"]=full;assert.ok(isStore(store));});
test("legacy sessions without a date still load; invalid dates are rejected",()=>{const store=emptyStore();store.active.Push=newSession("Push",{});delete store.active.Push.date;assert.ok(isStore(store));store.active.Push.date="2026-02-31";assert.equal(isStore(store),false);assert.throws(()=>newSession("Push",{},"not-a-date"));});
test("next targets use completed reps and keep increases conditional",()=>{const e=workouts.Push[0];assert.match(nextAim(e,[{kg:6,reps:10,done:true}]),/3 × 12.*6 kg/);assert.match(nextAim(e,Array.from({length:3},()=>({kg:6,reps:12,done:true}))),/If every set felt easy/);});
test("history sorts by chosen session date, not entry time",()=>{const a=newSession("Push",{},"2026-09-10");const b=newSession("Pull",{},"2026-09-20");assert.equal(sortedHistory([a,b])[0].id,b.id);assert.equal(sessionDate(a),"2026-09-10");});
